client/src/components/ProTx/components/maps/MainMap.js
Line 164 - set the outline color to black.
* [FP-123](https://jira.tacc.utexas.edu/browse/FP-123)
1.
=> Update MainMap.js to use black outline

client/src/components/ProTx/components/charts/MainChart.js, client/src/components/ProTx/components/dashboard/DashboardDisplay.js, client/src/components/ProTx/components/dashboard/DisplayLayout.js, client/src/components/ProTx/components/maps/MainMap.js, client/src/components/ProTx/components/util.js
Allows users to select geographic/map feature (e.g. a specific county) by clicking on it
* [COOKS-34](https://jira.tacc.utexas.edu/browse/COOKS-34)
* Allow user to select a geographic feature (e.g. county)
* Disable leaflet maps default behavior of double-click zoom
1. Click on a county while viewing maltreatment
2. Notice county has red outline and that county id is displayed above chart (just for illustrative purposes)
3. Click on the same county to deselect it or a different county to change selection
I added two follow on tickets:
* https://jira.tacc.utexas.edu/browse/COOKS-55
* https://jira.tacc.utexas.edu/browse/COOKS-54
=> Task/COOKS-34: Allows users to select map feature

client/src/components/ProTx/components/util.js
Allows us to select geographic features (e.g. counties) even if they have no value.   Return transparent style if no value for feature so that we can then click on the feature to select it.
* [COOKS-63](https://jira.tacc.utexas.edu/browse/COOKS-63)
1. Click on counties without a value and confirm that they can be selected.
=> task/COOKS-63:  Allow selection of geographic features without a value

client/src/components/ProTx/components/dashboard/MaltreatmentSelector.css
This makes the rsmc dropdown component match the default styles the other dropdown menus are using in PPRD and PROD.
It retains the purple accent on teh dropdown header.
* None
1. Use Analysis Reports dropdown selector, make sure it is purple header text, white bg, black dropdown text
=> RMSC Component CSS Styles Reset

client/src/components/ProTx/components/charts/ReportChart.js, client/src/components/ProTx/components/dashboard/DashboardDisplay.js, client/src/components/ProTx/components/dashboard/ReportDisplayLayout.js
Hot fixes for report as observed features wasn't being shown on map.
* [COOKS-70](https://jira.tacc.utexas.edu/browse/COOKS-70)
- 
- Fix locking of report to 2019/observedFeatures
- Handle both map types in ReportChart (Only using observedFeatures at the moment)
- 
1. Ensure you can go to `report` and see the selected demographic feature on the map
2. Ensure that you can't see maltreatment data or switch years.
=> Task/COOKS-70: hot fixes for report

client/src/components/ProTx/components/dashboard/DashboardDisplay.js
Lock `report `to county and disable related dropdown
None
* Lock `report `to county and disable related dropdown
=> Hotfix: Lock report to county and disable changing it

client/src/components/ProTx/components/dashboard/AnalysisDisplayLayout.js, client/src/components/ProTx/components/dashboard/ReportDisplayLayout.js, client/src/components/ProTx/components/maps/MainMap.js
Fixes issues where selected geographic feature lost its highlighting when options (year, type etc) were changed.
* [COOKS-66](https://jira.tacc.utexas.edu/browse/COOKS-66)
* Preselect selected geographic feature when recreating layers
1. Select area
2. Change settings (like maltreatment types)
3. Confirm area is still highlighted with black outline
=> task/COOKS-66: keep geographic selection when switching options

client/src/components/ProTx/components/dashboard/DashboardDisplay.js, client/src/components/ProTx/components/maps/MainMap.js, client/src/components/ProTx/components/maps/intervalColorScale.js
Swaps out the colors array used in the MainMap component. 
Also fixes two tiny linting errors where double quotes were used instead of single quotes in MainMap and DashboardDisplay.
* [COOKS-76](https://jira.tacc.utexas.edu/browse/COOKS-76)
1. Run project and check map colors.
Old colors:
New colors:
=> Change static color scale used on map to greater contrast

client/src/components/ProTx/components/charts/PredictiveFeaturesTable.css, client/src/components/ProTx/components/charts/PredictiveFeaturesTable.js, client/src/components/ProTx/components/charts/ReportChart.js, client/src/components/ProTx/components/charts/predictiveFeaturesTableData.js
Completed redesigning the ReportChart and the PredictiveFeaturesTable. Table now uses data instead of hard coded values. Content is in place to handle feature selection display when chart plot is completed. ReportCHart is currently commenting out Plots and Instructions until Plot is completed. This addresses tasks COOKS-78 and COOKS-80.
* [COOKS-78](https://jira.tacc.utexas.edu/browse/COOKS-78)
* [COOKS-80](https://jira.tacc.utexas.edu/browse/COOKS-80)
1. Build and run the project. Use the PredictiveFeatures map under Analysis Reports.
When no selection is passed into the plot (the only state for the current time being).
When the current selectedFeature value is passed into the chart. This is not enabled yet, need to develop a method to generate the selectedFeature data object the chart …
=> COOKS-78 & COOKS-80 - ReportsChart Layout Tweaks

client/src/components/ProTx/components/data/meta.js
Remove percent from demographic feature labels
* [COOKS-115](https://jira.tacc.utexas.edu/browse/COOKS-115)
1. Go to https://cep.dev/protx/demographics
2. Click on percents and then ensure all labels no longer have the word "percent"
=> COOKS-115:  Remove 'percent' from demographic feature labels

server/portal/templates/includes/nav_portal.raw.html
Hotfix to remove login per Tracy's request
https://tacc-team.slack.com/archives/GQW4Q8HLG/p1633966581118900?thread_ts=1633966549.118600&cid=GQW4Q8HLG reflects that we can't use CMS container settings yet.
=> task/COOKS-125: Hotfix to remove login

server/protx/data/api/demographics.py, server/protx/data/api/views.py
* Add fix for median gross rent
* Add workaround for COOKS-148 where some display values for true/false are stored as 1 or "1" or 0 or "0".
* [COOKS-147](https://jira.tacc.utexas.edu/browse/COOKS-147)
1. https://prod.protx.tacc.utexas.edu/protx/demographics/
2. Select county and select median gross rent
3. Confirm all dropdown menus display correct entries
:
=> Task/COOKS-125  fix for COOKS-147

client/package-lock.json, client/package.json, client/src/components/ProTx/components/maps/MainMap.css, client/src/components/ProTx/components/maps/MainMap.js, client/src/redux/sagas/protx.sagas.js, server/protx/data/api/urls.py, server/protx/data/api/views.py
Initial work for COOKS-155 which adds:
* resources data endpoint to backend 
* initial markers of resources on map
* [COOKS-15](https://jira.tacc.utexas.edu/browse/COOKS-155) <- initial work and doesn't close ticket.
* added backend routes for resources
* added initial frontend display of resources
1. Locally, get example resources database and copy to `~/protx-data/resources.db`
2. View https://cep.dev/protx/demographics
TODO
=> Cooks 155 add resources data endpoint

client/src/components/ProTx/components/maps/MainMap.js, client/src/redux/sagas/protx.sagas.js, server/protx/data/api/views.py
Add ability to display different resources by having a layer for each resource category (and displayed in layers control)
* [COOKS-155](https://jira.tacc.utexas.edu/browse/COOKS-155)
* Add individual layer for each resource category to layers control
* Add resources display information to response
1. View `/protx/maltreatment`
2. View layer control and confirm categories
TODO here or in follow on
=> Task/COOKS-155: Add resources navigation

client/src/components/ProTx/components/charts/ChartInstructions.css, client/src/components/ProTx/components/charts/ChartInstructions.js
Changes the description of each report to no longer reference time spans and adds in the map layer and globe icons.
* [COOKS-170](https://jira.tacc.utexas.edu/browse/COOKS-170?src=confmacro)
1. Build and urn p[roject.
2. Read report instructions.
=> Updated the verbiage and added in the needed icons.

server/protx/data/api/demographics.py
Additions to `demographics.py` to support server-side queries for ProTX portal data. Changes enable generation of "simple" demographics line charts and enable generation of easier-to-interpret "detailed" demographics histograms. **These changes may break the current "detailed" demographics charts.**
* [COOKS-152](https://github.com/TACC/protx/tree/COOKS-152)
1. Implements `pearson_kurtosis` method to calculate distribution skew
2. Rewrote method `hist_to_bar` to return more simplified data
3. Added method `get_bin_edges` to (a) detect skewed distributions and (b) implement special binning for skewed distributions
4. Updated return data structure in `demographic_data_prep` to properly return y-axis range for histograms.
5. Adds element ['fig_aes']['center'] to `data_response` variable in …
=> add kurtosis and adaptive bin sizing to demographic_data_prep workflow

server/conf/docker/docker-compose-dev.all.debug.yml
I created a container for the generated vector tiles (see this repo https://github.com/TACC/protx-geospatial-data). 
Previously, John and I have been tar-ing them up and moving them around which is no fun.
* [FP-197](https://jira.tacc.utexas.edu/browse/COOKS-197)
1. Check that map loads with vectors tiles.
We should update our two deployments to use these containers as well. (ticket -> https://jira.tacc.utexas.edu/browse/COOKS-198)
=> Use protx-geospatial container for vector tiles

server/poetry.lock, server/protx/data/api/decorators.py, server/protx/data/api/demographics.py, server/protx/data/api/views.py, server/pyproject.toml
Add simple caching mechanism to speed up responses
* [COOKS-199](https://jira.tacc.utexas.edu/browse/COOKS-199)
1.  Go to /protx/maltreatment or /protx/demographics and notice time to load (>20 or 30 secs?)
2. Subsequent reloads of that page should now be much quicker
3. Invalidate cache by changing timestamp of dbs: `touch ~/protx-data/cooks.db ~/protx-data/resources.db`
4. Reload app and notice that it takes a long time again
TODO
=> Add simple cached results for some responses

client/src/components/ProTx/components/maps/MainMap.js
Fixes bug where county selection is always displayed as an incorrect color.
* [COOKS-153](https://jira.tacc.utexas.edu/browse/COOKS-153)
The `showRate` value was missing in the `getFeatureStyle` call when click-selecting county features. Thus, it gave the incorrect `featureValue`, 1. 
1. Select a county.
2. Ensure that the color is correct and only the border is drawn.
N/A
=> Bug/COOKS-153: County selection incorrect display color

client/src/components/ProTx/components/maps/MainMap.js
Reset selected feature style on zooming out.
* [COOKS-181](https://jira.tacc.utexas.edu/browse/COOKS-181)
The `dataLayer` state seemed to not work with the set layer (`newDataLayer`).
Not just with `resetFeatureStyle` but also with `setFeatureStyle`.
I think something funky goes on with the shallow copy on the state hook and it's referring to the wrong object pointer.
So, I tried setting the layer with a ref hook. And it worked 😃
1. Select a map feature so that it zooms and creates a border.
2. Click the globe to zoom out.
3. Ensure that the style is reset.
=> Bug/COOKS-181: Fix feature deselection style on zoom out.

client/src/components/ProTx/components/dashboard/DashboardDisplay.js, server/conf/docker/docker-compose-dev.all.debug.yml
Pinned the cms container image tag in docker-compose.all until we unfork from upstream, otherwise we will encounter build errors. 
Switched the default unit value for the charts so that Percents are used on Demographics and count is used on Maltreatment. 
* [COOKS-238](https://jira.tacc.utexas.edu/browse/COOKS-238)
* [COOKS-240](https://jira.tacc.utexas.edu/browse/COOKS-240)
- Pinned image tag.
- Switched default unit to use in charts.
1. Build and run project.
I am encountering an inconsistent rendering issue with the DisplaySelector labelRadioBtn1 not being actively selected in the UI by default, even though the component state is correct and renders the plot using the  correct unit on map selection.
=> Pin CMS image Tag, set default unit types for charts Maltreatment, Demographics

server/portal/apps/onboarding/steps/project_membership.py, server/portal/apps/onboarding/steps/project_membership_unit_test.py, server/portal/fixtures/tas/tas_project_users.json
Bringing in upstream fix for project membership (see https://github.com/TACC/Core-Portal/pull/596) 
> When checking if a user is a project member, the membership step uses pytas's `projects_for_user `(ie. /v1/projects/username/) returns a list of projects but does not include projects who don't have any allocation. Using get_project_users is a better approach and avoids this issue.
* [COOKS-211](https://jira.tacc.utexas.edu/browse/COOKS-211)
* [COOKS-230](https://jira.tacc.utexas.edu/browse/COOKS-230)
* [FP-1514](https://jira.tacc.utexas.edu/browse/FP-1514)
See https://github.com/TACC/Core-Portal/pull/596. 
but really, i don't think it needs to be retested.
=> Fix project membership step to handle allocation-less projects (#596)

client/src/components/ProTx/components/dashboard/MaltreatmentSelector.css
Change 3rd-party dropdown to white background (dark text).
* [COOKS-229](https://jira.tacc.utexas.edu/browse/COOKS-229)
1. Remove all black/white/gray background and text color styles.
2. Unset one background color.
⚠️ I tested against staging (pre-prod) code.
1. Open Maltreatment page.
2. Open dropdown.
3. See white background.
4. Interact (hover, select, clear, deselect, choose).
5. Confirm no weirdness related to code change.
I didn't do anything else because ticket focuses on background and I am under the impression ProTX is in rush hour right now, so I git-r-done.
=> COOKS-229: White Dropdown Bkgd for Maltreat. App

client/src/components/ProTx/components/maps/MainMap.js, client/src/components/ProTx/components/shared/dataUtils.js
Refactor the label on the map legend.
* [COOKS-265](https://jira.tacc.utexas.edu/browse/COOKS-265)
1. Go to https://cep.dev/protx/analytics
2. Go to https://cep.dev/protx/demographics
3. In https://cep.dev/protx/demographics, you can switch between percent and total and note change
4. Click on a county just to get a feel for how things look.
=> task/COOKS-265: refactor label on map legend

server/portal/apps/onboarding/steps/project_membership.py
fix onboarding link by pulling in upstream/cepv2 fix.  
* [COOKS-247](https://jira.tacc.utexas.edu/browse/COOKS-247)
1. I think just review code would be sufficient.
=> task/COOKS-247: fix onboarding link

client/src/components/ProTx/components/dashboard/DashboardDisplay.js
Made default demographics selection to 'Population 17 years and under'
* [COOKS-266](https://jira.tacc.utexas.edu/browse/COOKS-266)
Change default selection.
1. Ensure that "Population 17 years and under" is selected by default in demographics route.
=> Task/COOKS-266: Make default selector for demographics population 17 years and under.

client/src/components/ProTx/components/maps/MainMap.js
Set Child and Youth Services and Cook Children's Locations on by default.
* [COOKS-264](https://jira.tacc.utexas.edu/browse/COOKS-264)
Changed `MainMap.js`.
1. Ensure that Child and Youth Services and Cook Children's Locations are on by default.
I wasn't sure if I should check directly with the `NAICS_CODE` or through the resource description (requires extra check).
=> Task/COOKS-264: Add 2 default checked map layers.

client/src/components/ProTx/components/shared/dataUtils.js
Recognize when no values were found for maltreatment.  For example, a user selects a year and a single maltreatment type where there is no data for that year, we need to recognize that.
1. Select Sex Trafficking and year 2011.
=> Hotfix: Handle no maltreatment data

client/src/components/ProTx/components/charts/AnalyticsDetails.js, client/src/components/ProTx/components/charts/DemographicsDetails.js, client/src/components/ProTx/components/charts/MaltreatmentDetails.js, client/src/components/ProTx/components/dashboard/DashboardDisplay.js, client/src/components/ProTx/components/dashboard/MaltreatmentSelector.css, client/src/components/ProTx/components/shared/dataUtils.js, server/protx/data/api/demographics.py, server/protx/data/api/maltreatment.py, server/protx/data/api/utils/plotly_figures.py
* https://jira.tacc.utexas.edu/browse/COOKS-236
* https://jira.tacc.utexas.edu/browse/COOKS-237
* https://jira.tacc.utexas.edu/browse/COOKS-217
* https://jira.tacc.utexas.edu/browse/COOKS-209
* `plotly_figures.py` now expects data from 2020 for demographics plots
* Plot legends now have line breaks if text strings are greater than 25 characters. Two implementations:
* `cooks.db` table `display_data` adds a column "DISPLAY_TEXT_PLOT" which includes line breaks (`<br>`) in text strings. Maltreatment plots automatically pull from this field.
* Demographics plots continue to use the original "DISPLAY_TEXT" field because units are added to the text string when the plot is created, which lengthens the strings and makes the pre-determined breaks poorly positioned. For these plots, a …
=> Legend linebreaks
