- client/src/components/ProTx/MainMap.js
- client/src/components/ProTx/index.js
- client/src/components/Workbench/index.js
- server/conf/nginx/nginx.conf
- server/portal/settings/settings.py
- server/portal/urls.py
- server/protx/data/admin.py
- server/protx/data/apps.py
- server/protx/data/models.py
- server/protx/data/tests.py
- server/protx/data/urls.py
- server/protx/data/views.py
Add placeholder app
* [COOKS-11](https://jira.tacc.utexas.edu/browse/COOKS-11)
- Add django app for frontera
- Add placeholder frontend app
1. Run and go to cep.dev/protx
> Add placeholder app

- client/package-lock.json
- client/package.json
- client/src/components/ProTx/MainMap.css
- client/src/components/ProTx/MainMap.js
- client/src/components/ProTx/MapProviders.js
- client/webpack.common.js
Add leaflet map with initial base map layers from old demo
* [FP-COOKS-11](https://jira.tacc.utexas.edu/browse/COOKS-11)
* [FP-COOKS-1](https://jira.tacc.utexas.edu/browse/COOKS-1)
> Add leaflet map with initial base map layers from old demo

- client/src/components/ProTx/MainMap.js
- client/src/components/ProTx/MainMap.module.scss
- server/protx/data/views.py
Add control bar with example drop down selectors 
* [COOKS-1](https://jira.tacc.utexas.edu/browse/COOKS-1)
* [COOKS-11](https://jira.tacc.utexas.edu/browse/COOKS-11)
* Add control bar with example drop down selectors 
* Remove requirement that user has to be logged in to see map
> Refactor map add initial layout

- client/src/components/ProTx/DashboardDisplay.css
- client/src/components/ProTx/DashboardDisplay.js
- client/src/components/ProTx/DashboardDisplay.module.scss
- client/src/components/ProTx/MainMap.js
- client/src/components/ProTx/MainMap.module.scss
- client/src/components/ProTx/index.js
Fix spinner so that its in center of page
* [COOKS-35](https://jira.tacc.utexas.edu/browse/COOKS-35)
* [COOKS-18](https://jira.tacc.utexas.edu/browse/COOKS-18)
* Fix spinner so that its in center of page
* Fix classes for mainmap as some classes got reintroduced in merging conflicts
* Refactor index.js
1. Load page and confirm spinner is centered
> Task/cooks 18----spinner and other fixes

- client/src/components/ProTx/components/meta.js
Add new demographic features
* [COOKS-47](https://jira.tacc.utexas.edu/browse/COOKS-47)
0. Get data (see https://confluence.tacc.utexas.edu/display/UP/Demo+map+notes+Jul+8th+data) (**Note:  I need to get the two updated json files on pprd or corral for you to pull**)
1. View new geographic features
Todo
> Add new demographic features

- client/src/components/ProTx/components/dashboard/MaltreatmentSelector.css
Fixes dropdown selection highlight color issues.
* No ticket, quick patch.
Added extra selectors that clobber all hover styles in the rmsc element dropdown-container.
1. Use dropdown.
> Minor fix to address bug in dropdown selector for maltreatment.

- client/src/components/ProTx/components/dashboard/MaltreatmentSelector.css
Fixed the last o the styling to reset the component to vanilla state while keeping a few minor tweaks.
* hotfix
1. Types dropdown looks clean and vanilla.
> Updates to MaltreatmentSelector.css

- client/src/components/ProTx/components/charts/ChartInstructions.js
- client/src/components/ProTx/components/charts/MaltreatmentTypesPlot.js
- client/src/components/ProTx/components/dashboard/DashboardDisplay.js
- client/src/components/ProTx/components/maps/MainMap.js
- client/src/components/ProTx/components/maps/MapProviders.js
Fix some warnings
* [COOKS-72](https://jira.tacc.utexas.edu/browse/COOKS-72)
> Task/COOKS-72: fix warnings

- client/src/components/ProTx/components/dashboard/DashboardDisplay.js
- client/src/components/ProTx/components/dashboard/DisplaySelectors.js
- client/src/components/ProTx/components/meta.js
Limit selections in report page
* [COOKS-79](https://jira.tacc.utexas.edu/browse/COOKS-79)
> COOKS-79 - Limit selections in report page

- client/src/components/ProTx/components/charts/PredictiveFeaturesPlot.js
- client/src/components/ProTx/components/charts/ReportChart.js
- client/src/components/ProTx/components/dashboard/DashboardDisplay.module.scss
Fixes some minor things in current main
None
* Centers loading spinner
* Hides instructions in report
* Hide work-in-progress feature in report chart
* Removes some used code
> Hotfix: center spinner, remove instructions and work-in-progress chart in report

- client/src/components/ProTx/components/dashboard/AnalyticsDashboard.js
Tweak to the header message text.
Quick fix to Header text.
* None
1. None
Did I escape this correctly in the string?
> Updated AnalyticsDashboard.js hostName in header msg.

- client/src/components/ProTx/components/charts/PredictiveFeaturesChart.js
- client/src/components/ProTx/components/dashboard/DashboardDisplay.js
* Fix county issue in demographics
* Hide work-in-progress chart and related instructions in analytics
None
1. Check that you can get to non-county data in https://cep.dev/protx/demographics
2. Check that plot is hidden in https://cep.dev/protx/analysis
> Hotfix: county issue in demographics and hide work-in-progress chart

- client/src/components/ProTx/components/shared/plotUtils.js
Minor fixes
* [COOKS-125](https://jira.tacc.utexas.edu/browse/COOKS-125)
* fix first subplot which was showing lots of ticks (causing a grey like background).
> Task/cooks 125  fix focal value other fixes

- client/src/components/ProTx/components/dashboard/DisplaySelectors.js
- client/src/components/ProTx/components/shared/dataUtils.js
Changed lowercase k to uppercase as per instructions for hard coded UI locations. Updated database already copied to PPRD to fix data-related capitalization changes.
Turns 'k' into 'K'.
* [COOKS-157](https://jira.tacc.utexas.edu/browse/COOKS-157)
Turned 'k' into 'K'.
1. Build and run, look for 'K' instead of 'k'.
> Capitalization completed

- client/src/components/ProTx/components/maps/MainMap.css
- client/src/components/ProTx/components/maps/MainMap.js
Redid the way the marker popup is generated and rendered to be simpler and cleaner.
* None.
Made the object simpler and more efficient.
1. Run project, look at map marker popup.
> Quick Tweak

- server/portal/templates/includes/nav_portal.raw.html
This reverts commit 2c95fe1a8998ec1035b3821cc49c1bb4257146e8.
> Add login button

- client/src/components/ProTx/components/charts/ChartInstructions.js
- client/src/components/ProTx/components/charts/ObservedFeaturesChart.js
- client/src/components/ProTx/components/charts/ObservedFeaturesPlot.css
- client/src/components/ProTx/components/charts/ObservedFeaturesPlot.js
- client/src/components/ProTx/components/dashboard/DashboardDisplay.js
- client/src/components/ProTx/components/maps/MainMap.js
Requested UI adjustments for Tracy:
* update instructions text
* remove display of single year value as graph now showing summary over multiple years
**Note this PR also fixes a bug where we removed the needed filtering of observation points missing lat/long**
* [TASK/COOKS-176](https://jira.tacc.utexas.edu/browse/COOKS-176)
> Task/cooks 176 UI adjustments

- client/src/components/ProTx/components/charts/ObservedFeaturesPlot.css
- client/src/components/ProTx/components/charts/ObservedFeaturesPlot.js
Remove current long sentence after header.
* [COOKS-194](https://jira.tacc.utexas.edu/browse/COOKS-194)
Changed to the source data footnote verbiage under the plot, beneath the header selected feature information.
1. Build & Run project.
2. Verify that the wording is correct.
> Text fixes for Demographics Chart

- client/src/components/ProTx/components/charts/MaltreatmentTypesPlot.css
- client/src/components/ProTx/components/charts/MaltreatmentTypesPlot.js
- client/src/components/ProTx/components/charts/ObservedFeaturesPlot.css
Remove current long sentence after header.
Refactor layout to match Demographics.
* [COOKS-128](https://jira.tacc.utexas.edu/browse/COOKS-128)
Changed to the source data footnote verbiage under the plot, beneath the header selected feature information.
1. Build & Run project.
2. Verify that the wording is correct.
> Text fixes for Maltreatment Chart

- client/src/components/ProTx/components/maps/MainMap.js
Switching to another base map as bw-mapnik from wmflabs.org is having issues
https://wiki.openstreetmap.org/wiki/Tile_servers
and then status of wmflabs.org is the following: https://tiles.wmflabs.org/bw-mapnik/9/264/179.png/status
* [COOKS-202](https://jira.tacc.utexas.edu/browse/COOKS-202)
> Use different base map

- client/src/components/ProTx/components/charts/MaltreatmentChart.js
- client/src/components/ProTx/components/charts/ObservedFeaturesChart.js
- client/src/components/ProTx/components/charts/PredictiveFeaturesChart.js
- client/src/components/ProTx/components/charts/PredictiveFeaturesPlot.css
- client/src/components/ProTx/components/charts/PredictiveFeaturesPlot.js
Add static verbiage about data time ranges after header.
Refactor chart header layout to match Demographics & Maltreatment.
* [COOKS-193](https://jira.tacc.utexas.edu/browse/COOKS-193)
- Changed to the source data footnote verbiage under the plot, beneath the header selected feature information.
- Refactored the basic plot layout to match Demographics and Maltreatment.
1. Build & Run project.
2. Verify that the wording and layout are correct.
3. In order to render the plot graph for testing, set the `PredictiveFeaturesChart.js` boolean for `showPlot`on [line 17](https://github.com/TACC/protx/blob/59cf601c73bde083da20c95ab5952634689d3c11/client/src/components/ProTx/components/charts/PredictiveFeaturesChart.js#L17)  to `true`.
We need to do one more refactor across all three Chart & Plot …
> Text fixes for Analytics Chart and Layout Refactor

- client/src/components/ProTx/components/maps/MainMap.js
Quick tweak to the formatting of mainMap.js so prettier is happy in the linter.
* None.
Indentation fix.
1. RUn project as usual.
None.
None.
> Linter formatting tweak

- client/src/components/ProTx/components/maps/MainMap.js
Alphabetized resource categories (Not have Misc as first type of Resources).
Temporary fix until https://jira.tacc.utexas.edu/browse/COOKS-241 is resolved.
* [COOKS-239](https://jira.tacc.utexas.edu/browse/COOKS-239)
Alphabetically sorted resource categories.
1. Ensure that resource categories are sorted alphabetically.
> Task/COOKS-239: Sort resource categories alphabetically.

- client/src/components/ProTx/components/dashboard/DashboardDisplay.js
- server/protx/data/api/demographics.py
- server/protx/data/api/maltreatment.py
* https://jira.tacc.utexas.edu/browse/COOKS-236
* https://jira.tacc.utexas.edu/browse/COOKS-237
* https://jira.tacc.utexas.edu/browse/COOKS-217
* https://jira.tacc.utexas.edu/browse/COOKS-209
- Fixed spelling mismatch inconsistency between files (`variables`).
- Added better assertion handling to gracefully handle assertion failure errors.
- Minor formatting cleanup.
1. Run project, everything works (map tile son maltreatment percentages are. off until UI auto-select is fixed - see notes).
Still need to add UI handling for auto-selecting all categoriues under maltreatment if value is set to percentage by the user, otherwise the maptiles render incorrect colors and the key values are incorrect.
> Fix for a few errors in the PR that break the code. 

- server/protx/data/api/maltreatment.py
Remove logic selecting all maltreatment types. This behavior will be reworked/discussed later.
> Hotfix: Remove asserts related to maltreatment types
